### ISSUE TITLE
Develop enums for Study, Biospecimen, Data File, Assay and add ontology terms

### ISSUE THREAD

**Issue by lopierra** [include-dcc/include-linkml#108]
Add/review/finalize enums/ontology terms for the following Study/Dataset fields (see notes [here](https://docs.google.com/spreadsheets/d/1LPTrq_4TfBBoQ1cwD06kcIZhTYGF0WsVSgF_A4ySZIE/edit#gid=655259626)):

- [ ] Biospecimen https://github.com/include-dcc/include-linkml/issues/169
- [ ] Assay https://github.com/include-dcc/include-linkml/issues/170
- [x] Research Domain https://github.com/include-dcc/include-linkml/issues/174
- [x] Participant Lifespan Stage https://github.com/include-dcc/include-linkml/issues/175
- [x] Study Design https://github.com/include-dcc/include-linkml/issues/179
- [ ] Clinical Data Source Type https://github.com/include-dcc/include-linkml/issues/176
- [ ] Data Category https://github.com/include-dcc/include-linkml/issues/177
- [ ] Data Type https://github.com/include-dcc/include-linkml/issues/180
- [ ] Experimental Strategy https://github.com/include-dcc/include-linkml/issues/178
- [ ] Experimental platform https://github.com/include-dcc/include-linkml/issues/171
- [ ] Access Limitations https://github.com/include-dcc/include-linkml/issues/172
- [ ] Access Restrictions https://github.com/include-dcc/include-linkml/issues/173

-----------
Pierrette's comments: 
For Biospecimen/Assay/DataFile, we have discussed EDAM, OBI, etc. Sample Type, File Type, etc.

Currently, we have a controlled vocabulary, but using a pre-existing ontology might allow us to have more relationships/hierarchies, e.g., between Data Categories & Types. Maybe we could annotate Experimental Platform and then have a search widget for users to search parent categories?

**Comment by lopierra** [comment]
Application ontology will also be very useful for the new Study/Datatset fields. Please see the yellow highlighted cells in [this sheet](https://docs.google.com/spreadsheets/d/1LPTrq_4TfBBoQ1cwD06kcIZhTYGF0WsVSgF_A4ySZIE/edit#gid=655259626&range=F1).

**Comment by lopierra** [comment]
Related to #159

**Comment by twhetzel** [comment]
Matt and I have discussed two options for including enums from ontology terms, (1) an explicit enumeration of terms in enum definitions or (2) referencing subsets of terms defined in an external Application Ontology. 

Currently the preference is for (1) to define a fixed set of terms in the schema in advance because the LinkML docs say "this works well if the vocabulary is known in advance and it is a relatively small number of terms" [1].

[1] https://linkml.io/linkml/faq/modeling.html#how-do-i-constrain-the-value-of-a-slot-using-an-ontology-or-vocabulary

**Comment by lopierra** [comment]
Closing since we now have separate tickets for this, plus the slots might be changing
