### ISSUE TITLE
Update Schematic to handle edges with Classes as the range

### ISSUE THREAD

**Issue by putmantime** [include-dcc/include-linkml#110]
Currently we have to transform the object of semantic triples to the string ID for the referenced object because schematic doesn't handle URIs.
We need to design a way for schematic to do this so the hardcoded logic doesn't live in the JSON-LD transformer.

**Comment by putmantime** [comment]
@milen-sage

**Comment by milen-sage** [comment]
Yes, handling uri's is not a big lift in schematic since a lot of the logic to do that is actually already there; it's just not exposed. We are also refactoring how data models are parsed, which would facilitate handling that even more. Let's sync up in about two sprints (i.e. four weeks) and we should be able to start working on this.
